// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getDSTP
NumericMatrix getDSTP(NumericVector parms, int trialType, int nTrials, double dt, double var);
RcppExport SEXP flankr_getDSTP(SEXP parmsSEXP, SEXP trialTypeSEXP, SEXP nTrialsSEXP, SEXP dtSEXP, SEXP varSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type parms(parmsSEXP);
    Rcpp::traits::input_parameter< int >::type trialType(trialTypeSEXP);
    Rcpp::traits::input_parameter< int >::type nTrials(nTrialsSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type var(varSEXP);
    __result = Rcpp::wrap(getDSTP(parms, trialType, nTrials, dt, var));
    return __result;
END_RCPP
}
// getSSP
NumericMatrix getSSP(NumericVector parms, int trialType, int nTrials, double dt, double var);
RcppExport SEXP flankr_getSSP(SEXP parmsSEXP, SEXP trialTypeSEXP, SEXP nTrialsSEXP, SEXP dtSEXP, SEXP varSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type parms(parmsSEXP);
    Rcpp::traits::input_parameter< int >::type trialType(trialTypeSEXP);
    Rcpp::traits::input_parameter< int >::type nTrials(nTrialsSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type var(varSEXP);
    __result = Rcpp::wrap(getSSP(parms, trialType, nTrials, dt, var));
    return __result;
END_RCPP
}
